os: linux
language: python
sudo: false # faster builds

matrix:
  include:
    - python: 3.6
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: 2.7
      env: TOXENV=py

install: pip install tox

script: tox

notifications:
  email: false
